# conf/base/parameters.yml
min_support: 0.03
min_confidence: 0.40
min_lift: 1.2

# ------------------------------------------------------------------------
# Parámetros globales (comunes a preprocesado)
# ------------------------------------------------------------------------
data:
  train_split: 0.8
  random_seed: 42

# ------------------------------------------------------------------------
# Parámetros específicos para Random Forest
# ------------------------------------------------------------------------
rf_grid:
  n_estimators: [100, 200, 300]
  max_depth: [5, 10, 15, None]
  min_samples_split: [2, 4, 6]
  class_weight: ["balanced"]

# ------------------------------------------------------------------------
# Parámetros específicos para XGBoost
# ------------------------------------------------------------------------
xgb_grid:
  n_estimators: [100, 200]
  max_depth: [3, 5, 7]
  learning_rate: [0.05, 0.1, 0.2]
  subsample: [0.8, 1.0]
  colsample_bytree: [0.8, 1.0]
  scale_pos_weight: [1]  # ajusta si hay desbalance
